/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimalPage: typeof import('./src/components/product-page/AnimalPage.vue')['default']
    CaptureSequencing: typeof import('./src/components/service-page/CaptureSequencing.vue')['default']
    CommonPage: typeof import('./src/components/product-page/CommonPage.vue')['default']
    CropPage: typeof import('./src/components/product-page/CropPage.vue')['default']
    CustomizedPage: typeof import('./src/components/product-page/CustomizedPage.vue')['default']
    DataService: typeof import('./src/components/service-page/DataService.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('./src/components/common/ElCarousel.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ProblemSolving: typeof import('./src/components/resource-page/ProblemSolving.vue')['default']
    ProductPage: typeof import('./src/components/common/ProductPage.vue')['default']
    ResequencingPage: typeof import('./src/components/service-page/ResequencingPage.vue')['default']
    ResourceDownload: typeof import('./src/components/resource-page/ResourceDownload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleRequirements: typeof import('./src/components/resource-page/SampleRequirements.vue')['default']
    SwiperComponent: typeof import('./src/components/common/SwiperComponent.vue')['default']
    TranscriptomeSequencing: typeof import('./src/components/service-page/TranscriptomeSequencing.vue')['default']
  }
}
